import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CirclePlus, Search, Settings } from "lucide-react";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Link Keeper",
  description: "Generated by custor Dev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster position="top-center" />
        <div className="  px-6 bg-dark-blue-gradient bg-gradient-to-br from-blue-900 to-white min-h-screen flex items-center justify-center">
          {children}
        </div>
      </body>
    </html>
  );
}
