import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CirclePlus, Search, Settings } from "lucide-react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Link Keeper",
  description: "Generated by custor Dev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-[80vh] px-6 ">{children}</div>
      </body>
    </html>
  );
}
