import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CirclePlus, Search, Settings } from "lucide-react";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@/components/theme-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Link Keeper",
  description: "Generated by custor Dev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster position="top-center" />
          <div className="min-h-screen items-center justify-center px-6   ">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
